name: mmgbsa_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9          
  - numpy>=1.24,<1.27  
  - pandas=1.3.5
  - scipy=1.10         
  - scikit-learn=1.3   
  - shap=0.47.2        
  - matplotlib=3.7.3
  - seaborn=0.13.2
  - plotly=5.17.0
  - joblib=1.4.2
  - selenium=4.27.1
  - webdriver-manager=4.0.2
  - mdanalysis=2.4.3
  - hyperopt=0.2.7
  - pyspark=3.5.4
  #- ambertools=21.12
  #- gromacs=2022.1
  - jupyterlab=4.2